### PR TITLE
feat(SDK): Windows Mixed Reality Support

### PR DESCRIPTION
**Pull request by tomwim**
Windows MIxed Reality Support for VRTK (Issue: https://github.com/thestonefox/VRTK/issues/1565):
- Add Mixed Reality Headset and Controllers
- Add Mixed Reality to every example scene
- Add controller visualization (with GLTF and new Newtonsoft.JSON.dll)
- Update with newest MRTK scripts and plugins
- Include Touchpad Two in Controller Events
- Add highlighting and tooltips for Mixed Reality Controller
- Add .NET scripting backend support
- Bug fixing

Known issues:
- Haptic feedback is irregular (and does not work in Editor)
- Area teleport has an increasing offset in Example Scene 12 (https://github.com/Innoactive/IA-unity-VR-toolkit-VRTK/issues/19)
- No interaction with cube in Example Scene 35 (https://github.com/Innoactive/IA-unity-VR-toolkit-VRTK/issues/21)
- No falling and height offset in Example Scene 37 (https://github.com/Innoactive/IA-unity-VR-toolkit-VRTK/issues/20)

Thanks to @DDReaper @thestonefox @bddckr @if1live @vladkol

### CODE REVIEW

**Comment by thestonefox** [comment]
I think you may need to rebase in the latest version of the 3.3.0-alpha branch into your branch, it looks like there's a number of things in this commit that may have already been done.

**Comment by tomwim** [comment]
Thanks, just double checked. It's already rebased to the latest 3.3.0-alpha (e9cbee0f512f1a32703e04946cda345ff004187f) and there are no conflicts.

**Comment by skyteks** [comment]
I played around with it the last 8 hours, trying to make it work, without much success. I used this pull as well as the 3.3.0-alpha (pure).
At both versions I was sometimes stuck in the ground and the controllers mostly weren't there at all.
Bruteforce restarting the game (in editor) made them appear some times but only when I was stuck in the ground, and then the controllers would be above the ground. Sometimes the handedness in WindowsMR_TrackedObject wasn't set in the controllers.

**Comment by 265lutab** [comment]
How do I download the version with WMR support?

**Comment by tomwim** [comment]
@skyteks the 3.3.0 alpha (pure) does not have WMR included, only SteamVR Mixed Reality support.

Being stuck in the ground is caused by Stationary Tracking instead of Room Scale Tracking. Stationary puts you at (0, 0, 0), so in the ground. The camera has a script where you can toggle if you want Room Scale to be forced which is sometimes necessary. You also need Room Scale Setup in the Mixed Reality Portal for that.
Room Scale is for _normal_ applications while Stationary is for something like video players.

About the controllers not being shown. I sometimes had this issue too and I feel like it's an Editor problem. Closing (and opening) the Mixed Reality Portal usually helped. In a built project it works fine.

Before I opened the pull request I went through all scenes and double checked if the handedness is set, quite annoying...I just realized switching from Standalone to UWP resets the Handedness to unknown (as well as some other things), at least in the current scene. This is caused by code that only works with UWP.

@265lutab you can get this branch for testing https://github.com/Innoactive/IA-unity-VR-toolkit-VRTK/tree/feature/windows-mixed-reality-rebased

**Comment by 265lutab** [comment]
@tomwim Thank you. What version of unity does this support and is it meant to not have the holotoolkit also imported to the project? I'm getting a number of errors saying thinks like:
`Assets/VRTK/Source/SDK/WindowsMR/Additional/GLTF/Scripts/Schema/Sampler.cs(99,14): error CS0101: The namespace `GLTF' already contains a definition for `MagFilterMode'
`

**Comment by tomwim** [comment]
@265lutab I developed with MRTP-5 since that is the latest version recommended by Microsoft. It should work with 2017.2 as well but not guaranteed. Follow issue https://github.com/thestonefox/VRTK/issues/1565 for more information.

VRTK is VRTK, whatever you add is your choice but this works as it is.

**Comment by 265lutab** [comment]
I'm currently using MRTP-5

**Comment by DDReaper** [comment]
Just FYI, 2017.2.1 includes all the MRTP fixes, as does 2017.3RC2
These are now the recommended builds for Mixed Reality :D

**Comment by 265lutab** [comment]
Is it recommended to include SteamVR or remove it when using VRTK for Mixed Reality?

**Comment by tomwim** [comment]
If you want to use Standalone with Steam VR then use Steam VR, if you want to use UWP then use this branch.

**Comment by DDReaper** [comment]
Any indications when this will be merged in to the Alpha branch? @thestonefox / @tomwim 
Anything I can do to help that along?

**Comment by thestonefox** [comment]
I need to go through it and test the PR, then go over the PR code and make sure it's all good in the hood.

I've got a VR laptop now, so i just need the time to do it, with Christmas fast approaching I'm not sure it will be this side of Christmas (maybe even after the New Year).

**Comment by DDReaper** [comment]
I did a load of testing on the previous branch and did run this through when it showed up.
Will retest on 2017.3 (now that it's out and has all the MR fixes) and update

**Comment by thestonefox** [comment]
poo, I made a conflict. Example scene 25 is in conflict now :(

**Comment by thestonefox** [comment]
Ok quick look at the repo and the first thing I've noticed is all of the windows SDK scripts have been included. These shouldn't be included with VRTK, it's adding a large bulk of windows specific code to the repo which people may not ever use.

Shouldn't this stuff be downloaded separately and have instructions included of how to download and integrate that?

**Comment by DDReaper** [comment]
There shouldn't be any windows related code, as it's built in to windows itself, there isn't even an SDK.
There is the gLTF importer, but that is just a stop gap as Unity doesn't have an importer itself yet. (MRTK does the same)

**Comment by thestonefox** [comment]
@DDReaper this pull request contains a directory called `Source/SDK/WindowsMR/Additional`

That additional folder is full of Windows MR extensions that shouldn't be included in VRTK. These extensions should be downloaded separately the same way that SteamVR is downloaded separately.

**Comment by tomwim** [comment]
It's as @DDReaper says, that stuff is from MRTK and redone to work for VRTK. I agree with you though, that it is unnecessary for people that do not want Windows MR. But the whole Controller part is not as nicely done as with Oculus and Steam and there is not a supported package/source for Windows MR. 

But I could rework it and try to make a second Repo where the Additional stuff can be downloaded and integrated. That won't happen before new year though.

**Comment by DDReaper** [comment]
The stuff in the additional folder is only available as source and isn't downloadable atm. The hope is unity will add GLTF support in the future and this won't be needed.

Everything in that folder is either gLTF code or supporting WMR classes for VRTK AFAIK. 
@tomwim can you confirm?

**Comment by thestonefox** [comment]
Isn't all the gLTF stuff purely to display controller models though?

To me, I feel this Additional folder is massive overkill. If anything it should be a seaprate package like the way Oculus Avatar is, then in VRTK it wouldn't support displaying controller models unless you have that separate package (that's how Oculus SDK does it).

**Comment by DDReaper** [comment]
OK, fair enough. If we have a prescient in another SDK, then that makes sense. However the package will need to be made available somehow, as it's not provided by anyone currently.

I noticed @tomwim S comment saying he may look in to that in the new year. Hopefully it can be done before the 3.3 release

**Comment by thestonefox** [comment]
I'm going to try and take a look at making a separate repo for it over the Christmas period. It would probably be better being owned by MRTK though, but if I can do a lot of the grunt work then maybe it can just be copied straight over.

**Comment by DDReaper** [comment]
It's not really an MRTK thing either.  The project is also separate there.
It's been "sort of" provided by MS until Unity get their act together.

But having it as a "pluginable" project would be hugely beneficial.  Just the gLFT importer/renderer of course, there are other scripts in that folder that @tomwim created for VRTK boilerplate

**Comment by DDReaper** [comment]
It's not really an MRTK thing either.  The project is also separate there.
It's been "sort of" provided by MS until Unity get their act together.

But having it as a "pluginable" project would be hugely beneficial.  Just the gLFT importer/renderer of course, there are other scripts in that folder that @tomwim created for VRTK boilerplate.

**Comment by thestonefox** [comment]
Ok cool, I'll try get the model stuff as a separate repo, then pick out the bits that are core to vrtk

**Comment by DDReaper** [comment]
Righteo, if you want me to help / test, just shout :D

**Comment by tomwim** [comment]
@thestonefox did you already start with the new repo? I have more time now and could do what you planed

**Comment by thestonefox** [comment]
@tomwim I was going to start the vrtk integration today, but was going to do the controller model repo after, so if you have time to do that separate repo that just handles controller models then i could just look at hooking into that

**Comment by tomwim** [comment]
I'll let you know when I am done.

**Comment by DDReaper** [comment]
Let me know where you are putting that repo @tomwim and I'll see if I can loop the MRTK team in with it.  Might as well have one repo to rule them all :D

**Comment by tomwim** [comment]
Repo and branch for VRTK:
https://github.com/Innoactive/IA-unity-VR-toolkit-VRTK/tree/feature/windows-mixed-reality-refactoring

@thestonefox I created this because I had to make changes in the WindowsMR_TrackedObject. I don't know if you already found the time to do some changes as well. If we eventually drop this changes I'll be happy, too.

Repo and branch for extension:
https://github.com/Innoactive/VRTK-Windows-MR-Extension/tree/release/vrtk-3.3.0-alpha

It now contains everything GLTF related and the visualizing scripts.

Not included is:
- InteractionSourceExtension (handles Haptic Feedback)
- WindowsApiChecker 
- WindowsMR_Camera (makes sure the Camera is setup properly)
- WindowsMR_ControllerManager (more or less just an empty container)
- WindowsMR_TrackedObject (handles Controller Input)
- All VRTK SDK scripts (Controller, Defines etc)

I had to exclude the initial visualization from the TrackedObject class and include it in the WindowsMR_ControllerVisualizer.

The VRTK itself won't work without the extension yet because the SDK_WindowsMRController relies on the Visualizer to set the Controller Model ready. Need to find a workaround for that. But it is a start.

@DDReaper Yes, every help is welcome and I agree, the less repos and overhead and confusion the better!

**Comment by tomwim** [comment]
Is it a problem if the SDK_WindowsMRController has a reference to the WindowsMR_ControllerVisualization (which is included in the extension)? It will break WinMR without the extension but that is not what we want anyways, right? You cannot use VRTK for Oculus without the Oculus stuff.

**Comment by bddckr** [comment]
An SDK in VRTK is always dependent on a vendor SDK package to be installed, but that's about it. For Oculus models to show up you actually need to also import Oculus Avatar for example, but VRTK works fine without Avatar being imported.

Maybe this should be the same for WMR, so no dependency on visualization?

**Comment by LordSkittles** [comment]
Is there an ETA on this being merged into 3.3.0-alpha?

**Comment by DDReaper** [comment]
FYI @thestonefox / @tomwim , just found an existing external repositiory for gLTF which is managed by the open group who provide the standard.
https://github.com/KhronosGroup/UnityGLTF
This should probably be subModuled for WMR support

**Comment by DDReaper** [comment]
Any update on this PR getting merged?  Anything I can do to help? @tomwim @thestonefox

**Comment by thestonefox** [comment]
@DDReaper this PR probably won't get merged, but will be used to form a new PR.

I'm about a month behind on the stuff I want to get finished on VRTK for 3.3.0 (especially since I've rebuilt all the example scenes!). Hopefully soon we'll have WMR support :)

**Comment by DDReaper** [comment]
Like I said, shout if you want me to pitch in @thestonefox 
Kronos updated their GLTF lib already since this PR anyway and the MRTK have done so as well.

**Comment by tomwim** [comment]
@thestonefox sorry for the huge delay... I had no time anymore to do anything on my work PC but finally got a proper graphics card at home. I would rework everything this weekend or did you start working on native WMR support?

Which branch do you recommend to rebase to, since there are a lot of changes from your side?

**Comment by thestonefox** [comment]
@tomwim no worries, as soon as the new example scenes PR is merged then the WMR stuff is ready to be worked on.

I'm happy to do it, as most of it is going to be just taking your existing SDK and migrating it over.

As for controller models, I still think that should be a separate repo (maybe already is from MRTK?) and we treat it like we treat oculus avatar rather than bake in controller model support into VRTK.

**Comment by moscartong** [comment]
Hi @thestonefox . I got a Windows mixed reality headset recently and been digging around the [MRTK](https://github.com/Microsoft/MixedRealityToolkit-Unity) repo. Is there anything I could help regarding the WMR support?

**Comment by tomwim** [comment]
@DDReaper Do you know if anyone is working on the Controller models with a newer version of GLTF? I saw it's still a quite early iteration and since then the repo from Khronos changed a lot

**Comment by DDReaper** [comment]
We updated MRTK to use the latest version of the Kronos source.  Wasn't massively different, just streamlined the asset download.

**Comment by tomwim** [comment]
Thanks, found it. Missed that it's included in the Dev branch not in master.

**Comment by DDReaper** [comment]
Correct and in stabalisation (which is the next release)

**Comment by thestonefox** [comment]
@tomwim @DDReaper does this mean that we can just piggy back on that khronos stuff for WMR controller representation in VRTK as well?

Then VRTK is just the SDK bridge and we use a separate asset for controllers? (like oculus avatar)

**Comment by tomwim** [comment]
Yes that is the idea. Like you said before you do not like all that plugins and scripts in VRTK if it is _just_ for visualization, which I agree on.

I am working on a repo that can be included which handles controller visualization. It is based on the MRTK implementation (which includes Khronos' GLTF to load models on runtime) but unfortunately I cannot copy everything 1:1.

**Comment by DDReaper** [comment]
The big difference between WMR and other SDK's is that the controller models are provided by the platform and are not contained in any package.  Which is good for support as MS can update them without affecting anyone, but requires a little more magic for SDK's enabling this.

**Comment by bddckr** [comment]
SteamVR doesn't contain them either, it streams the models in at runtime. (At least the Unity SteamVR plugin does.)

**Comment by DDReaper** [comment]
Thanks @bddckr , wasn't aware of that based on the current VRTK implementation.

**Comment by tomwim** [comment]
@DDReaper @thestonefox 
I updated and refactored my VRTK branch and added all the controller visualization stuff to an extra repository.

VRTK: [feature/windows-mixed-reality-refactoring ](https://github.com/Innoactive/IA-unity-VR-toolkit-VRTK/tree/feature/windows-mixed-reality-refactoring)
VRTK-Windows-MR-Extension: [release/vrtk-3.3.0-alpha](https://github.com/Innoactive/VRTK-Windows-MR-Extension)
 
Just add the extension to the Unity project. It works fine for me and I hope it does in general and for everyone. I added some explanation to the README of the Extension.

Issues:
- Haven't updated the example scenes and SDK Setup yet. Will do so when I get your okay to rebase to latest VRTK 3.3.0 alpha. Updating these scenes broke so often for me that I'd rather do it once and not multiple time...
- The material looks really weird. Super dark and metallic. It's the same shader and material as in MRTK so I have no idea why it's broken. Maybe you have an idea @DDReaper ?
- Unfortunately same issues as mentioned in the original post

**Comment by thestonefox** [comment]
@tomwim if you get the new 3.3.0 alpha branch then there are new example scenes and all of the SDK setup stuff is done in 1 scene which is additively loaded in, so you only need to update 1 scene :)

The legacy scenes are still there, but you don't have to bother with them.

**Comment by tomwim** [comment]
Perfect. Am I right that the only scene I have to change is VRTK_SDKManager_Constructor and the prefab in there?

**Comment by thestonefox** [comment]
@tomwim yup that's all

**Comment by tomwim** [comment]
Closed and opened a new PR #1743
